const $ = (id) => document.getElementById(id);
const E = {
  lang: $('lang'), saveProject: $('saveProject'), loadProject: $('loadProject'),
  pickImage: $('pickImage'), clear: $('clear'), imageInput: $('imageInput'),
  previewImg: $('previewImg'), previewHint: $('previewHint'),
  fileName: $('fileName'), fileDim: $('fileDim'), style: $('style'), size: $('size'),
  newGame: $('newGame'), resume: $('resume'), fit: $('fit'), reset: $('reset'),
  zoomOut: $('zoomOut'), zoomIn: $('zoomIn'), time: $('time'), progress: $('progress'),
  best: $('best'), status: $('status'), viewport: $('viewport'), stage: $('stage'),
  slots: $('slots'), placed: $('placed'), tray: $('tray'), records: $('records'),
  modal: $('modal'), finishText: $('finishText'), closeModal: $('closeModal'),
};
const T = {
  en:{appTitle:'Turn into a Jigsaw Puzzle',appSubtitle:'Load any image, split it, and play instantly.',language:'Language',saveProject:'Save Project',loadProject:'Load Project',source:'Source',loadImage:'Load Image',clear:'Clear',noImage:'No image loaded yet.',file:'File',dimensions:'Dimensions',setup:'Setup',style:'Puzzle style',styleJigsaw:'Classic jigsaw',styleSquare:'Square tiles',piecesPerSide:'Pieces per side',newGame:'Create Puzzle',resume:'Resume',status:'Status',timer:'Time',progress:'Progress',best:'Best',idleState:'Load an image to start.',boardHint:'Drag pieces from the right tray. Pan the board by dragging empty space. Zoom with buttons or mouse wheel.',fit:'Fit View',resetView:'Reset View',tray:'Piece tray',records:'Records',completeTitle:'Puzzle completed',continue:'Continue',completed:'Completed in {time}.',newRecord:'New record!',noRecord:'No record yet.',currentBest:'Current best: {time}',saveSuccess:'Project saved.',loadSuccess:'Project loaded.',loadImageFirst:'Load an image first.',puzzleReady:'Puzzle created. Start dragging pieces from the tray.',puzzleResumed:'Puzzle resumed.',clearDone:'Puzzle cleared.',saveHint:'Save a project file to continue later.',recordsForCurrent:'Best time for this puzzle'},
  zh:{appTitle:'圖片變拼圖',appSubtitle:'載入任意圖片，切成拼圖並直接遊玩。',language:'語言',saveProject:'儲存拼圖檔',loadProject:'載入拼圖檔',source:'來源',loadImage:'載入圖片',clear:'清除',noImage:'尚未載入圖片。',file:'檔案',dimensions:'尺寸',setup:'設定',style:'拼圖樣式',styleJigsaw:'經典拼圖',styleSquare:'方塊拼圖',piecesPerSide:'每邊碎片數',newGame:'建立拼圖',resume:'繼續遊玩',status:'狀態',timer:'時間',progress:'進度',best:'最佳紀錄',idleState:'先載入圖片即可開始。',boardHint:'從右側拼圖槽拖曳碎片到棋盤。拖曳空白處可平移畫面，使用按鈕或滑鼠滾輪可縮放。',fit:'適合視窗',resetView:'重置視角',tray:'拼圖槽',records:'紀錄',completeTitle:'拼圖完成',continue:'繼續',completed:'完成時間：{time}。',newRecord:'新的紀錄！',noRecord:'尚無紀錄。',currentBest:'目前最佳：{time}',saveSuccess:'拼圖檔已儲存。',loadSuccess:'拼圖檔已載入。',loadImageFirst:'請先載入圖片。',puzzleReady:'拼圖已建立，從右側開始拖曳碎片。',puzzleResumed:'已繼續上次進度。',clearDone:'已清除目前拼圖。',saveHint:'可儲存拼圖檔以便之後繼續。',recordsForCurrent:'此拼圖的最佳時間'},
  ja:{appTitle:'画像をジグソーパズルに変換',appSubtitle:'任意の画像を読み込み、分割してそのまま遊べます。',language:'言語',saveProject:'パズルを保存',loadProject:'パズルを読み込む',source:'画像',loadImage:'画像を読み込む',clear:'クリア',noImage:'まだ画像が読み込まれていません。',file:'ファイル',dimensions:'サイズ',setup:'設定',style:'パズルの種類',styleJigsaw:'通常のジグソー',styleSquare:'四角パズル',piecesPerSide:'1辺の分割数',newGame:'パズルを作成',resume:'続きから',status:'状態',timer:'時間',progress:'進捗',best:'ベスト',idleState:'画像を読み込むと開始できます。',boardHint:'右側のトレイからピースをドラッグします。空白部分をドラッグすると盤面を移動、ボタンやマウスホイールで拡大縮小できます。',fit:'全体表示',resetView:'表示を戻す',tray:'ピーストレイ',records:'記録',completeTitle:'完成しました',continue:'続ける',completed:'完成時間: {time}。',newRecord:'新記録です！',noRecord:'記録なし',currentBest:'現在の最短: {time}',saveSuccess:'保存しました。',loadSuccess:'読み込みました。',loadImageFirst:'先に画像を読み込んでください。',puzzleReady:'パズルを作成しました。右側のピースをドラッグしてください。',puzzleResumed:'前回の続きから再開しました。',clearDone:'現在のパズルをクリアしました。',saveHint:'あとで続けられるように保存できます。',recordsForCurrent:'このパズルの最短記録'}
};
const LS = {lang:'jigsaw-lang-v1',last:'jigsaw-last-v1',records:'jigsaw-records-v1'};
const C = {tray:5,pad:30,cell:108};
const S = {lang:'en',imageName:'',imageData:'',imageHash:'',imageW:0,imageH:0,style:'jigsaw',size:4,seed:0,boardW:0,boardH:0,pieces:[],map:new Map(),pool:[],tray:new Array(C.tray).fill(null),placed:0,running:false,completed:false,startAt:0,elapsed:0,transform:{x:0,y:0,s:1},drag:null,pan:null,records:JSON.parse(localStorage.getItem(LS.records)||'{}')};
const t = (k,o={}) => (T[S.lang]||T.en)[k].replace(/\{(\w+)\}/g,(_,x)=>o[x]??'');
const clamp = (v,a,b)=>Math.max(a,Math.min(b,v));
const hash = (s)=>{let h=2166136261; for (let i=0;i<s.length;i++){h^=s.charCodeAt(i); h=Math.imul(h,16777619);} return (h>>>0).toString(16);};
const rnd = (seed)=>{let a=seed>>>0; return()=>{a|=0; a=(a+0x6D2B79F5)|0; let t=Math.imul(a^(a>>>15),1|a); t^=t+Math.imul(t^(t>>>7),61|t); return ((t^(t>>>14))>>>0)/4294967296;};};
const shuf = (a,r)=>{a=a.slice(); for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1)); [a[i],a[j]]=[a[j],a[i]];} return a;};
const fmt = (ms)=>{ms=Math.max(0,Math.floor(ms)); const m=Math.floor(ms/60000), s=Math.floor((ms%60000)/1000), x=ms%1000; return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(x).padStart(3,'0')}`;};
const loadImg = (src)=>new Promise((res,rej)=>{const i=new Image(); i.onload=()=>res(i); i.onerror=rej; i.src=src;});
const fileToData = (f)=>new Promise((res,rej)=>{const r=new FileReader(); r.onload=()=>res(r.result); r.onerror=rej; r.readAsDataURL(f);});
const saveRecords = ()=>localStorage.setItem(LS.records,JSON.stringify(S.records));
const el = (tag, cls='')=>{const n=document.createElement(tag); if(cls) n.className=cls; return n;};
function applyTexts(){document.querySelectorAll('[data-i18n]').forEach(n=>{const k=n.dataset.i18n; n.textContent=t(k);}); E.style.querySelector('[value="jigsaw"]').textContent=t('styleJigsaw'); E.style.querySelector('[value="square"]').textContent=t('styleSquare'); document.documentElement.lang=S.lang;}
function setStatus(k,o){E.status.textContent=t(k,o);}
function updateUI(){E.time.textContent=fmt(currentMs()); E.progress.textContent=`${S.placed} / ${S.pieces.length}`; E.best.textContent=S.records[key()]?.bestMs!=null?fmt(S.records[key()].bestMs):t('noRecord'); renderRecords();}
function currentMs(){return S.running ? S.elapsed + (performance.now()-S.startAt) : S.elapsed;}
function key(){return S.imageHash ? `${S.imageHash}:${S.size}:${S.style}` : '';}
function startTimer(){if(!S.running){S.running=true; S.startAt=performance.now();}}
function stopTimer(){if(S.running){S.elapsed=currentMs(); S.running=false;}}
function fit(){if(!S.boardW) return; const r=E.viewport.getBoundingClientRect(), s=clamp(Math.min((r.width-40)/S.boardW,(r.height-40)/S.boardH),.35,1.6); setTransform((r.width-S.boardW*s)/2,(r.height-S.boardH*s)/2,s);}
function setTransform(x,y,s){S.transform={x,y,s}; E.stage.style.transform=`translate(${x}px,${y}px) scale(${s})`;}
function boardPoint(cx,cy){const r=E.viewport.getBoundingClientRect(); return {x:(cx-r.left-S.transform.x)/S.transform.s, y:(cy-r.top-S.transform.y)/S.transform.s};}
function clearBoard(){E.slots.innerHTML=''; E.placed.innerHTML=''; E.tray.innerHTML=''; S.tray=new Array(C.tray).fill(null);}
function traySlots(){E.tray.innerHTML=''; for(let i=0;i<C.tray;i++){const s=el('div','tray-slot'); s.dataset.i=i; const idx=el('div','index'); idx.textContent=i+1; s.appendChild(idx); E.tray.appendChild(s);} }
function grid(){E.slots.innerHTML=''; for(let r=0;r<S.size;r++) for(let c=0;c<S.size;c++){const d=el('div','slot'); d.style.left=`${C.pad+c*C.cell}px`; d.style.top=`${C.pad+r*C.cell}px`; d.style.width=`${C.cell}px`; d.style.height=`${C.cell}px`; d.dataset.r=r; d.dataset.c=c; E.slots.appendChild(d);}}
function edgeGrid(n,rand){const g=[...Array(n)].map(()=>[...Array(n)].map(()=>({t:0,r:0,b:0,l:0}))); for(let r=0;r<n;r++) for(let c=0;c<n;c++){if(c<n-1){const v=rand()<.5?1:-1; g[r][c].r=v; g[r+1-1][c+1].l=-v;} if(r<n-1){const v=rand()<.5?1:-1; g[r][c].b=v; g[r+1][c].t=-v;}} return g;}
function drawPath(ctx,p){const {w,h,t,edges:e}=p, L=t, T0=t, R=w-t, B=h-t, qx=(R-L)/4, qy=(B-T0)/4, midX=(L+R)/2, midY=(T0+B)/2; ctx.beginPath(); ctx.moveTo(L,T0); if(e.t) {ctx.lineTo(L+qx,T0); ctx.quadraticCurveTo(midX,T0-t*e.t,R-qx,T0); ctx.lineTo(R,T0);} else ctx.lineTo(R,T0); if(e.r) {ctx.lineTo(R,T0+qy); ctx.quadraticCurveTo(R+t*e.r,midY,R,B-qy); ctx.lineTo(R,B);} else ctx.lineTo(R,B); if(e.b) {ctx.lineTo(R-qx,B); ctx.quadraticCurveTo(midX,B+t*e.b,L+qx,B); ctx.lineTo(L,B);} else ctx.lineTo(L,B); if(e.l) {ctx.lineTo(L,B-qy); ctx.quadraticCurveTo(L-t*e.l,midY,L,T0+qy); ctx.lineTo(L,T0);} else ctx.lineTo(L,T0); ctx.closePath();}
function pieceUrl(src,p){const c=document.createElement('canvas'); c.width=p.w; c.height=p.h; const g=c.getContext('2d'); g.save(); drawPath(g,p); g.clip(); g.drawImage(src,-p.bx+p.t,-p.by+p.t); g.restore(); g.save(); drawPath(g,p); g.lineWidth=2; g.strokeStyle='rgba(255,255,255,.22)'; g.stroke(); g.restore(); return c.toDataURL('image/png');}
function createPiece(p){const d=el('div','tray-piece'); d.dataset.id=p.id; d.style.width=`${Math.min(100,p.w)}px`; d.style.height=`${Math.min(100,p.h)}px`; d.innerHTML=`<img alt="" draggable="false" src="${p.url}">`; d.addEventListener('pointerdown',onPieceDown); p.el=d; return d;}
function drawTray(i){const s=E.tray.querySelector(`.tray-slot[data-i="${i}"]`); if(!s) return; s.querySelectorAll('.tray-piece,.drag-piece').forEach(n=>n.remove()); const p=S.tray[i]; if(!p) return; p.state='tray'; p.slot=i; const d=p.el; d.className='tray-piece'; d.style.position='absolute'; d.style.left='0'; d.style.top='28px'; d.style.width=`${Math.min(100,p.w)}px`; d.style.height=`${Math.min(100,p.h)}px`; d.style.cursor='grab'; s.appendChild(d);}
function nextPool(){const id=S.pool.shift(); if(!id) return null; const p=S.map.get(id); return p&&p.state==='pool'?p:nextPool();}
function refillTray(i){if(S.tray[i]) return; const p=nextPool(); if(!p) return; S.tray[i]=p; drawTray(i);}
function fillTray(){for(let i=0;i<C.tray;i++) refillTray(i);}
function createPieces(){const r=rnd(S.seed), n=S.size, bW=n*C.cell, bH=n*C.cell, src=document.createElement('canvas'); src.width=bW; src.height=bH; const g=src.getContext('2d'); const imgScale=Math.max(bW/S.imageW,bH/S.imageH); const dw=S.imageW*imgScale, dh=S.imageH*imgScale; g.drawImage(S.img,(bW-dw)/2,(bH-dh)/2,dw,dh); const edges=edgeGrid(n,r); S.boardW=bW+C.pad*2; S.boardH=bH+C.pad*2; S.pieces=[]; S.map=new Map(); S.pool=[]; for(let y=0;y<n;y++) for(let x=0;x<n;x++){const t=S.style==='jigsaw'?Math.max(12,Math.round(C.cell*.22)):0, p={id:`${y}-${x}`,r:y,c:x,bx:x*C.cell,by:y*C.cell,t,w:C.cell+t*2,h:C.cell+t*2,e:edges[y][x],state:'pool',slot:-1,el:null}; p.url=pieceUrl(src,p); createPiece(p); S.pieces.push(p); S.map.set(p.id,p);} S.pool=shuf(S.pieces.map(p=>p.id),r); E.stage.style.width=`${S.boardW}px`; E.stage.style.height=`${S.boardH}px`; grid();}
function renderPieces(){E.placed.innerHTML=''; S.pieces.filter(p=>p.state==='placed').forEach(p=>{const d=p.el; d.className='piece'; d.style.position='absolute'; d.style.left=`${C.pad+p.bx-p.t}px`; d.style.top=`${C.pad+p.by-p.t}px`; d.style.width=`${p.w}px`; d.style.height=`${p.h}px`; d.style.cursor='default'; E.placed.appendChild(d); const s=E.slots.querySelector(`.slot[data-r="${p.r}"][data-c="${p.c}"]`); if(s) s.classList.add('done');});}
function place(p){p.state='placed'; p.slot=-1; p.el.className='piece'; p.el.style.position='absolute'; p.el.style.left=`${C.pad+p.bx-p.t}px`; p.el.style.top=`${C.pad+p.by-p.t}px`; p.el.style.width=`${p.w}px`; p.el.style.height=`${p.h}px`; p.el.style.cursor='default'; E.placed.appendChild(p.el); S.placed++; renderPieces(); updateUI();}
function returnToTray(p,slot){const target=slot??S.tray.findIndex(Boolean); if(target<0){p.state='pool'; S.pool.unshift(p.id); return;} const current=S.tray[target]; if(current&&current!==p){current.state='pool'; current.slot=-1; S.pool.unshift(current.id); if(current.el.parentElement) current.el.remove();} S.tray[target]=p; drawTray(target);}
function dragStart(p,e){const rect=p.el.getBoundingClientRect(); const ox=e.clientX-rect.left, oy=e.clientY-rect.top, slot=p.slot; if(slot>=0){S.tray[slot]=null; drawTray(slot); refillTray(slot);} p.state='drag'; p.el.className='drag-piece'; p.el.style.position='fixed'; p.el.style.left=`${e.clientX-ox}px`; p.el.style.top=`${e.clientY-oy}px`; p.el.style.width=`${p.w}px`; p.el.style.height=`${p.h}px`; p.el.style.zIndex='999'; document.body.appendChild(p.el); S.drag={p,ox,oy,slot};}
function onPieceDown(e){const p=S.map.get(e.currentTarget.dataset.id); if(!p||p.state!=='tray') return; e.preventDefault(); dragStart(p,e); const move=v=>{if(!S.drag) return; S.drag.p.el.style.left=`${v.clientX-S.drag.ox}px`; S.drag.p.el.style.top=`${v.clientY-S.drag.oy}px`;}; const up=v=>{window.removeEventListener('pointermove',move); window.removeEventListener('pointerup',up); if(!S.drag) return; const d=S.drag; const bp=boardPoint(v.clientX,v.clientY); const inside=bp.x>=0&&bp.y>=0&&bp.x<=S.boardW&&bp.y<=S.boardH; const targetX=C.pad+p.bx+C.cell/2, targetY=C.pad+p.by+C.cell/2; const ok=inside&&Math.hypot(bp.x-targetX,bp.y-targetY)<=C.cell*.65; if(ok){place(p);} else returnToTray(p,d.slot); S.drag=null; maybeComplete(); updateUI();}; window.addEventListener('pointermove',move); window.addEventListener('pointerup',up,{once:true});}
function maybeComplete(){if(S.placed!==S.pieces.length) return; stopTimer(); S.completed=true; const ms=currentMs(), k=key(), prev=S.records[k]?.bestMs; S.records[k]={bestMs:prev==null?ms:Math.min(prev,ms),lastMs:ms,runs:(S.records[k]?.runs||0)+1,updatedAt:new Date().toISOString(),imageName:S.imageName,size:S.size,style:S.style}; saveRecords(); E.modal.classList.remove('hidden'); E.finishText.textContent=(prev==null||ms<prev?t('completed',{time:fmt(ms)})+' '+t('newRecord'):t('completed',{time:fmt(ms)})); updateUI();}
function renderRecords(){const k=key(), r=S.records[k]; E.records.innerHTML=''; const d=el('div','record'); d.innerHTML=`<div><strong>${t('recordsForCurrent')}</strong></div><div>${t('file')}: <strong>${S.imageName||'-'}</strong></div><div>${t('style')}: <strong>${S.style==='jigsaw'?t('styleJigsaw'):t('styleSquare')}</strong></div><div>${t('piecesPerSide')}: <strong>${S.size} × ${S.size}</strong></div><div>${t('best')}: <strong>${r?fmt(r.bestMs):t('noRecord')}</strong></div><div>${t('timer')}: <strong>${fmt(currentMs())}</strong></div>`; E.records.appendChild(d);}
function resetGame(){S.pieces=[]; S.map=new Map(); S.pool=[]; S.tray=new Array(C.tray).fill(null); S.placed=0; S.running=false; S.completed=false; S.startAt=0; S.elapsed=0; S.drag=null; S.pan=null; E.slots.innerHTML=''; E.placed.innerHTML=''; E.tray.innerHTML=''; E.previewImg.style.display='none'; E.previewHint.style.display='grid'; E.fileName.textContent='-'; E.fileDim.textContent='-'; E.time.textContent='00:00.000'; E.progress.textContent='0 / 0'; E.best.textContent='-'; E.modal.classList.add('hidden'); setTransform(0,0,1);}
function loadImage(file){return fileToData(file).then(async data=>{S.imageName=file.name; S.imageData=data; S.imageHash=hash(data); S.img=await loadImg(data); S.imageW=S.img.naturalWidth; S.imageH=S.img.naturalHeight; E.previewImg.src=data; E.previewImg.style.display='block'; E.previewHint.style.display='none'; E.fileName.textContent=S.imageName; E.fileDim.textContent=`${S.imageW} × ${S.imageH}`; setStatus('saveHint'); saveSnapshot(); updateUI();});}
function saveSnapshot(){if(!S.imageData) return; localStorage.setItem(LS.last,JSON.stringify({lang:S.lang,imageName:S.imageName,imageData:S.imageData,imageHash:S.imageHash,imageW:S.imageW,imageH:S.imageH,style:S.style,size:S.size,seed:S.seed,elapsed:currentMs(),running:S.running,completed:S.completed,transform:S.transform,tray:S.tray.map(p=>p&&p.id),placed:S.pieces.filter(p=>p.state==='placed').map(p=>p.id),pool:S.pool.slice()}));}
function buildProject(){return {version:1,lang:S.lang,imageName:S.imageName,imageData:S.imageData,imageHash:S.imageHash,imageW:S.imageW,imageH:S.imageH,seed:S.seed,style:S.style,size:S.size,elapsed:currentMs(),running:S.running,completed:S.completed,transform:S.transform,tray:S.tray.map(p=>p&&p.id),placed:S.pieces.filter(p=>p.state==='placed').map(p=>p.id),pool:S.pool.slice()};}
async function saveProject(){if(!S.imageData){alert(t('loadImageFirst')); return;} saveSnapshot(); const res=await window.puzzleApi.saveProject(`${(S.imageName||'puzzle').replace(/\.[^.]+$/,'').replace(/[^\w\-]+/g,'_').slice(0,40)||'puzzle'}_${S.size}x${S.size}_${S.style}.json`,JSON.stringify(buildProject(),null,2)); if(!res?.canceled) setStatus('saveSuccess');}
async function loadProject(){const res=await window.puzzleApi.loadProject(); if(!res?.content) return; const d=JSON.parse(res.content); await hydrate(d); setStatus('loadSuccess');}
async function hydrate(d){resetGame(); S.lang=T[d.lang]?d.lang:'en'; E.lang.value=S.lang; applyTexts(); S.imageName=d.imageName||'image'; S.imageData=d.imageData; S.imageHash=d.imageHash||hash(d.imageData); S.imageW=d.imageW||0; S.imageH=d.imageH||0; S.style=d.style==='square'?'square':'jigsaw'; S.size=clamp(+d.size||4,3,12); S.seed=+d.seed||((Date.now()^Math.random()*1e9)>>>0); E.style.value=S.style; E.size.value=String(S.size); S.img=await loadImg(S.imageData); E.previewImg.src=S.imageData; E.previewImg.style.display='block'; E.previewHint.style.display='none'; E.fileName.textContent=S.imageName; E.fileDim.textContent=`${S.imageW} × ${S.imageH}`; createPieces(); clearBoard(); traySlots(); const placed=new Set(d.placed||[]), tray=d.tray||[], pool=d.pool||[]; S.pool=pool.filter(id=>S.map.has(id)); S.placed=0; for(const p of S.pieces){if(placed.has(p.id)){p.state='placed'; S.placed++;}} renderPieces(); tray.forEach((id,i)=>{if(id&&S.map.has(id)){const p=S.map.get(id); p.state='tray'; p.slot=i; S.tray[i]=p; drawTray(i);}}); fillTray(); S.transform=d.transform||{x:0,y:0,s:1}; setTransform(S.transform.x||0,S.transform.y||0,S.transform.s||1); S.elapsed=+d.elapsed||0; S.completed=!!d.completed; S.running=!!d.running&&!S.completed; if(S.running) S.startAt=performance.now(); updateUI(); fit(); if(S.completed) {E.modal.classList.remove('hidden'); E.finishText.textContent=t('completed',{time:fmt(S.elapsed)});} saveSnapshot();}
function startNew(){if(!S.imageData){alert(t('loadImageFirst')); return;} S.style=E.style.value; S.size=clamp(+E.size.value||4,3,12); S.seed=(Date.now()^((Math.random()*1e9)|0))>>>0; S.imageHash=hash(S.imageData); createPieces(); clearBoard(); traySlots(); S.placed=0; S.elapsed=0; S.completed=false; S.running=true; S.startAt=performance.now(); fillTray(); renderPieces(); fit(); setStatus('puzzleReady'); saveSnapshot(); updateUI();}
function resume(){const raw=localStorage.getItem(LS.last); if(!raw) return; hydrate(JSON.parse(raw)).catch(console.error);}
function initLang(){S.lang=T[localStorage.getItem(LS.lang)]?localStorage.getItem(LS.lang):'en'; E.lang.value=S.lang; applyTexts();}
function bind(){E.lang.onchange=()=>{S.lang=E.lang.value; localStorage.setItem(LS.lang,S.lang); applyTexts(); updateUI();}; E.pickImage.onclick=()=>E.imageInput.click(); E.imageInput.onchange=async()=>{const f=E.imageInput.files?.[0]; if(f) await loadImage(f);}; E.newGame.onclick=()=>startNew(); E.resume.onclick=()=>resume(); E.clear.onclick=()=>{resetGame(); localStorage.removeItem(LS.last); setStatus('clearDone');}; E.saveProject.onclick=()=>saveProject().catch(console.error); E.loadProject.onclick=()=>loadProject().catch(console.error); E.fit.onclick=()=>fit(); E.reset.onclick=()=>fit(); E.zoomOut.onclick=()=>zoom(0.86); E.zoomIn.onclick=()=>zoom(1.16); E.closeModal.onclick=()=>E.modal.classList.add('hidden'); E.viewport.onpointerdown=e=>{if(e.target.closest('.piece,.tray-piece,.drag-piece')) return; const start={x:e.clientX,y:e.clientY,t:{...S.transform}}; S.pan=start; const move=v=>setTransform(start.t.x+(v.clientX-start.x),start.t.y+(v.clientY-start.y),start.t.s); const up=()=>{window.removeEventListener('pointermove',move); window.removeEventListener('pointerup',up); S.pan=null;}; window.addEventListener('pointermove',move); window.addEventListener('pointerup',up,{once:true});}; E.viewport.onwheel=e=>{e.preventDefault(); zoom(e.deltaY<0?1.08:.92,e.clientX,e.clientY);}; window.onresize=()=>S.boardW&&fit(); document.onkeydown=e=>{if(e.key==='Escape') E.modal.classList.add('hidden');};}
function zoom(f,cx,cy){if(!S.boardW) return; const r=E.viewport.getBoundingClientRect(), s=clamp(S.transform.s*f,.25,3.5), ax=cx==null?r.width/2:cx-r.left, ay=cy==null?r.height/2:cy-r.top, wx=(ax-S.transform.x)/S.transform.s, wy=(ay-S.transform.y)/S.transform.s; setTransform(ax-wx*s,ay-wy*s,s);}
function attachBoards(){E.stage.style.width='0px'; E.stage.style.height='0px';}
function boot(){initLang(); bind(); attachBoards(); traySlots(); fit(); updateUI(); const raw=localStorage.getItem(LS.last); if(raw){try{hydrate(JSON.parse(raw)).catch(console.error);}catch{}}}
boot();
setInterval(()=>{if(S.running){updateUI(); saveSnapshot();}},250);
function maybeComplete(){if(S.placed!==S.pieces.length) return; stopTimer(); S.completed=true; const ms=currentMs(), k=key(), prev=S.records[k]?.bestMs; S.records[k]={bestMs:prev==null?ms:Math.min(prev,ms),lastMs:ms,runs:(S.records[k]?.runs||0)+1,updatedAt:new Date().toISOString(),imageName:S.imageName,size:S.size,style:S.style}; saveRecords(); E.modal.classList.remove('hidden'); E.finishText.textContent=(prev==null||ms<prev?t('completed',{time:fmt(ms)})+' '+t('newRecord'):t('completed',{time:fmt(ms)})); updateUI();}
